server:
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/storeservice
            - classpath:config/userservice

#         searchLocations: file:///shopping-config-service/src/main/resources/config/storeservice