server:
  port: 5555

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
  server:
    waitTimeInMsWhenSyneEmpty: 5
  serviceUrl:
    defaultZone: http://localhost:8761/eureka

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    userservice: /user/**
    storeservice: /store/**