version: '3'
services:
  shopping_config:
    image: shopping/shopping-config
    ports:
     - "8888:8888"
  shopping_eureka:
    image: shopping/shopping-eureka
    ports:
     - "8761:8761"
  shopping_store:
    image: shopping/store-service
    ports:
     - "8001:8001"


