version: '3'
services:
  shopping_config:
    image: shopping/shopping-config
    environment:
      - "SPRING_PROFILES_ACTIVE=native"
    ports:
     - "8888:8888"
  shopping_eureka:
    image: shopping/shopping-eureka
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
     - "8761:8761"
  shopping_zuul:
    image: shopping/shopping-zuul
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "5555:5555"
  shopping_user:
    image: shopping/shopping-user
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8000:8000"
  database-user:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'shopping-user'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3301:3306'
  database-store:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'shopping-store'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3302:3306'
  shopping_store:
    image: shopping/shopping-store
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
     - "8001:8001"



